export const GET_COVID_DATA = 'GET_COVID_DATA';
export const GET_COVID_DEATH_BYDAY = 'GET_COVID_DEATH_BYDAY'
export const GET_COVID_DATA_AFRICA = 'GET_COVID_DATA_AFRICA'
export const GET_COVID_DATA_WORLD = 'GET_COVID_DATA_WORLD'